### PR TITLE
 Add public helper method for unwrapping

### PR DESCRIPTION
**Pull request by vuplea**
I have implemented as per issue https://github.com/ReflectionMagic/ReflectionMagic/issues/31

The problem is that extension methods do not support `dynamic` on the first parameter. I have added a non-extension static method.

### CODE REVIEW

**Comment by vuplea** [comment]
Another option would be to add an extension method for object `.AsObject()`, with the downside that it will be available for all expressions.

**Comment by davidebbo** [comment]
@jvandertil it's more your baby now. Would you have time to look at this one? I'm pretty disconnected from the .NET world :)

**Comment by jvandertil** [comment]
@davidebbo Will do :). 

@vuplea Thank you for sending a pull request to add the Unwrap functionality. I agree that we should add this somewhere in the library. 

However, I do not want to add it to the `PrivateReflectionUsingDynamicExtensions` class, only extension methods should go there.

I also considered a `AsObject()` or `Unwrap()` extension method on `object` but had the same concern as you, I want to avoid 'polluting' all types with extension methods. Also an extension method will have some usability issues, for example this will throw a runtime exception:
```cs
    public static class ObjectExtensions
    {
        public static void PrintThing(this object obj)
        {
            Console.WriteLine(obj.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var test = new object();

            test.AsDynamic().PrintThing();
        }
    }
```

@vuplea Could you take a look at my comment in #31? I want to make sure we get this functionality right :).

**Comment by vuplea** [comment]
@jvandertil 	I have provided more info on the issue page.
Basically, our need boils down to `serializer.AsDynamic().InternalDeserialize(message).GetType()` returning the type of the return value.

Also, as far as I can tell, extension methods don't work at all on `dynamic` -- IntelliSense was tricking me. A cast to `object` would enable it but offers bad usability. Thus leaving us with the option of a static method.
We will use a copy of Unwrap ourselves meanwhile. I will gladly update the PR if a decision is made.

**Comment by jvandertil** [comment]
Alright, merging this and will push out a beta package for you to test.

**Comment by vuplea** [comment]
Thanks a lot @jvandertil.
We've tested the `4.1.0-beta1` package and it works for our use case.

**Comment by jvandertil** [comment]
@vuplea Great! I have just pushed the 4.1.0 package, it should be available in a couple of minutes :). Thanks  again for bringing this up, and fixing it as well! 👍

**Pull request merged**
